---
# The period in seconds between scraping metrics
check_interval_seconds: 1 
http_server_port: 8000    
# List of processes which are checked (by name) 
check_processes:
  - java
  - chrome
  - python